### ISSUE TITLE
'mergerfs.ctl set' usage

### ISSUE THREAD

**Issue by 19wolf** [trapexit/mergerfs-tools#120]
Hello.
How do I use `mergerfs.ctl set`? The help page doesn't have any useful information. It just says:

```
usage: mergerfs.ctl set [-h] option value

positional arguments:
  option
  value

optional arguments:
  -h, --help  show this help message and exit
```

But there's no indication as to what options or values are available

**Comment by trapexit** [comment]
It's not listed here because they are defined in the main documentation: https://github.com/trapexit/mergerfs
