### ISSUE TITLE
feature: dry-run?

### ISSUE THREAD

**Issue by francoism90** [trapexit/mergerfs-tools#122]
I would like to test `mergerfs.dup` and `mergerfs.dedup`, but to be safe, I would like to perform a dry-run first.
Is this possible? Or can I use certain flags to perform a `--dry-run` first?

Thanks!

Edit: I assume running `mergerfs.fsck -f manual ..` allows to basically perform a dry-run?

**Comment by magma1447** [comment]
Dry run is default. There is an execute parameter to actually do anything.
