### ISSUE TITLE
Release/tag request

### ISSUE THREAD

**Issue by slashbeast** [trapexit/mergerfs-tools#123]
Hey. I am about to package mergerfs-tools into gentoo and noticed the repository has no releases or even tags there. For now I can make snapshot using date of top most commit as the version string, but would you consider to putting any version it it?

**Comment by trapexit** [comment]
This has always been a super casual project intended as a base for people to build things for their own needs. I could create releases but they really wouldn't mean much.

**Comment by slashbeast** [comment]
It is all right if there will be no tag, packaged it as mergerfs-tools-0_p20210502.

I think there's a fair amount of room for helper scripts around mergerfs. If ever you'd get a significant contribution to scripts around mergerfs would you consider to either turn mergerfs-tools into normal project, or bundling them alongside mergerfs itself?

**Comment by trapexit** [comment]
Sure, depending on what exactly it was. Most of these are intentionally bespoke. If something is seriously common it should be part of mergerfs proper.
