### ISSUE TITLE
mergerfs.fsck: getxattr() takes no keyword arguments

### ISSUE THREAD

**Issue by tholin** [trapexit/mergerfs-tools#25]
I'm trying to use mergerfs.fsck on a system with python-2.7.10 and pyxattr-0.5.5 and I get this error message.

```
Traceback (most recent call last):
  File "./mergerfs.fsck", line 192, in <module>
    main()
  File "./mergerfs.fsck", line 178, in main
    check_consistancy(fulldirpath,verbose,size,fix)
  File "./mergerfs.fsck", line 130, in check_consistancy
    paths = getxattr(fullpath,"user.mergerfs.allpaths").split('\0')
  File "./mergerfs.fsck", line 122, in getxattr
    return xattr.getxattr(path,key,symlink=True)
TypeError: getxattr() takes no keyword arguments
```

It runs if I remove the keyword argument on line 122 so it looks like
`return xattr.getxattr(path,key,True)`

**Comment by trapexit** [comment]
What platform is this? I was planning on moving all these to python3.

**Comment by tholin** [comment]
It's a Gentoo Linux system.
/usr/bin/python defaults to python2 on my system but python3 is also available as /usr/bin/python3. There is a Gentoo tool for setting which interpreter /usr/bin/python should point to. Having it set to python2 is usually the safe thing to do.

**Comment by trapexit** [comment]
Okay. Rather than fix this particular issue I'll port it to python3 and hopefully that'll help given pyxattr is no longer needed.

**Comment by qweasdzxc787** [comment]
Still having this issue, Fedora 23 x64.
