### ISSUE TITLE
dedup: ignore snapraid.content and snapraid.conf

### ISSUE THREAD

**Issue by henfri** [trapexit/mergerfs-tools#30]
Hello,

I think, it will be common practice to have a copy of snapraid.content and snapraid.conf on each drive.
This is intentional.

Nevertheless, dedup does dedup those files. Shouldn't they be ignored, when deduping?

Regards,
Hendrik

**Comment by trapexit** [comment]
Should they be explicitly ignored? No. 

In my experience I use dedup on specific subtrees so it's not likely I have that issue however the proper way to manage excluding files would be to do so like other tools (rsync) which have the ability to exclude files based on a fnmatch or regex.

I'll look into it. I have similar features in other tools.

**Comment by henfri** [comment]
Hello,

thanks for your answer. 
>Should they be explicitly ignored? No.
Why not? What would be a case in which it would be intended not to ignore them?

Regards,
Hendrik

**Comment by trapexit** [comment]
I don't know but it's not for me to say. snapraid is a specific product and my tools aren't for snapraid. They are generic. As such I'm happy to have the tool have ways to exclude files but I'm not interested in creating a blacklist of files from random products. Especially given the filenames you are referring to are user controllable and arbitrary.

**Comment by mtompkins** [comment]
Perhaps an approach like a default `.gitignore` but for mergerfs (i.e. `.mfsignore`)?  Then the community could offer some widely shared implementations like `snapraid`. 

Thanks for a very handy solution in any case.

**Comment by trapexit** [comment]
file filter added to dedup

**Comment by henfri** [comment]
Thanks!
