### ISSUE TITLE
merger.fs.balance error: getxattr

### ISSUE THREAD

**Issue by t-richter** [trapexit/mergerfs-tools#40]
Hi,
I'm using mergerfs under OpenMediaVault 2.2.14.
the balance script fails with the following message:
```

Traceback (most recent call last):
  File "/usr/local/bin/mergerfs.balance", line 156, in <module>
    main()
  File "/usr/local/bin/mergerfs.balance", line 128, in main
    if not ismergerfs(ctrlfile):
  File "/usr/local/bin/mergerfs.balance", line 26, in ismergerfs
    os.getxattr(path,'user.mergerfs.version')
AttributeError: 'module' object has no attribute 'getxattr'
```

BTW: For Linux noobs like me, it would be nice to have a proper "install" doc. Just a line what to download and where to drop it would have saved me ages.

**Comment by trapexit** [comment]
Sounds like the version of python3 installed is old. Can you tell me what `python3 -V` returns?

What do you mean by "what to download and where to drop it"? The scripts are mostly self contained and shouldn't need to to be placed anywhere in particular.

**Comment by t-richter** [comment]
python3 -V prompts:
`Python 3.2.3`

> The scripts are mostly self contained and shouldn't need to to be placed anywhere in particular. 

Sorry, I was not meaning to offend you, but for a noob like me this was totally unclear how to get this working. Until now I wasn't even aware, I'm dealing with a Python script. After looking for installation instructions on Google I just copied them over to a temp dir on my machine, which wasn't working ("command not found") .  I had to add it to $PATH first.

**Comment by trapexit** [comment]
Not offended just didn't understand what the problem was.

I expected basic *nix understanding. I can add a few lines to the doc. As for the version of Python. Not sure what I can do. The language is missing the needed feature. I guess I can put an error there but doesn't help you much.

**Comment by t-richter** [comment]
Is there a way to manually upgrade python3?

**Comment by trapexit** [comment]
I imagine so but I'm unfamiliar with how.

Does the package python3-xattr exist on OMV2?

**Comment by trapexit** [comment]
Try the latest version. Should work in Python 3.2
