### ISSUE TITLE
How to Load and Enable mergerfs-tools?

### ISSUE THREAD

**Issue by astrom0** [trapexit/mergerfs-tools#47]
Thanks for a very useful method for setting up a storage pool with mergerfs.

I've been able to make sense of all this for a Centos 7 setup. Not bad considering my limited skills with Linux. The mergerfs-tools are a logical next step but it's not clear to me how to install them, hence the title on this one.

Apologies if I missed something basic in the readme, wiki or the open & closed issues.

**Comment by trapexit** [comment]
Use the makefile or just copy the file to your bin directory of choice.

**Comment by astrom0** [comment]
Thanks for the assistance but your advice is based on assumed knowledge that I don't have. I'm after the dummies guide, please. I've searched the web and I haven't been able to find a step by step method that makes sense to me.

This piece is generally informative:
[Make_(software)](https://en.wikipedia.org/wiki/Make_(software))
but of limited use (see below).

This piece is a bit more focussed:
[Re: How to install MAKEFILE Post 2](https://ubuntuforums.org/showthread.php?t=1133668&s=5b322fe6cdb7f307a9e08e0001ec673c&p=7124823#post7124823)
but doesn't seem to line up with the offerings available here, so again it doesn't deliver for me.

I've tried the following:
1. Open terminal to the user home directory as per default
2. $ git clone https://github.com/trapexit/mergerfs-tools
3. $ cd ~/mergerfs-tools
4. $ sudo make -f Makefile
.. gives ..
`‘src/mergerfs.fsck’ -> ‘/usr/local/bin/mergerfs.fsck’
‘src/mergerfs.mktrash’ -> ‘/usr/local/bin/mergerfs.mktrash’
‘src/mergerfs.dedup’ -> ‘/usr/local/bin/mergerfs.dedup’
‘src/mergerfs.ctl’ -> ‘/usr/local/bin/mergerfs.ctl’
‘src/mergerfs.balance’ -> ‘/usr/local/bin/mergerfs.balance’
`
5. $ $ mergerfs.ctl -h
.. gives ..
`/usr/bin/env: python3: No such file or directory`

I'm trying to self help but I'm constrained by my lack of knowledge.

Thanks in advance.

**Comment by trapexit** [comment]
Install Python 3
