### ISSUE TITLE
mergerfs-tools.fsck hanging?

### ISSUE THREAD

**Issue by maxiedaniels** [trapexit/mergerfs-tools#48]
I'm running mergerfs-tools.fsck and it stops three files in (which happen to be .DS_Store files from a Mac Backup if that has anything to do with it). I'm using verbose mode.. not sure what else to try here.. it just gets to the third file and hangs.

**Comment by trapexit** [comment]
Are you sure it's not just scanning? It only prints things it finds in need of fixing.

**Comment by maxiedaniels** [comment]
Ah, that would make sense. I assumed verbose mode made it print the names of all files it scans.
