### ISSUE TITLE
mergerfs-tools.dup not available?

### ISSUE THREAD

**Issue by maxiedaniels** [trapexit/mergerfs-tools#49]
I installed the latest mergerfs-tools and when i run mergerfs-tools.dup it's saying not found. Did it get removed?

**Comment by magma1447** [comment]
I recently noticed the same thing, there is a binary in the src/ directory though.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs-tools/blob/master/src/mergerfs.dup

**Comment by trapexit** [comment]
It's not 'mergerfs-tools.dup' 

It's 'mergerfs.dup'

**Comment by maxiedaniels** [comment]
I meant to write 'mergerfs.dup' my bad. But I realized the issue I'm talking about is 'make' and 'make install' don't reference mergerfs.dup.

output from make:
`'src/mergerfs.fsck' -> '/usr/local/bin/mergerfs.fsck'
'src/mergerfs.mktrash' -> '/usr/local/bin/mergerfs.mktrash'
'src/mergerfs.dedup' -> '/usr/local/bin/mergerfs.dedup'
'src/mergerfs.ctl' -> '/usr/local/bin/mergerfs.ctl'
'src/mergerfs.balance' -> '/usr/local/bin/mergerfs.balance'
`

output from make install:
`removed '/usr/local/bin/mergerfs.fsck'
'src/mergerfs.fsck' -> '/usr/local/bin/mergerfs.fsck'
removed '/usr/local/bin/mergerfs.mktrash'
'src/mergerfs.mktrash' -> '/usr/local/bin/mergerfs.mktrash'
removed '/usr/local/bin/mergerfs.dedup'
'src/mergerfs.dedup' -> '/usr/local/bin/mergerfs.dedup'
removed '/usr/local/bin/mergerfs.ctl'
'src/mergerfs.ctl' -> '/usr/local/bin/mergerfs.ctl'
removed '/usr/local/bin/mergerfs.balance'
'src/mergerfs.balance' -> '/usr/local/bin/mergerfs.balance'`
