### ISSUE TITLE
Not able to run mergerfs.fsck under OMV3

### ISSUE THREAD

**Issue by t-richter** [trapexit/mergerfs-tools#51]
Sorry, when this turns out to be an noob question, but I'm still a beginner on linux systems 

Copied over the files to /usr/bin, which is part of my $PATH

Running mergerfs.fsck -h get "Permission denied" Error.
sudo mergerfs.fsck -h throws "Command not found"

running as root has the same effects.

python3 -V reads 3.4.2

Any ideas? 
Big thx , Timm

**Comment by trapexit** [comment]
is the file set to executable ? `chmod ugo+x /usr/bin/mergerfs.fsck`

**Comment by t-richter** [comment]
Ooops, forgot about this... after all I AM a linux noob.
Thanks for pointing this out, now it seems to work.
