### ISSUE TITLE
mergerfs.fsck does not report filename collisions

### ISSUE THREAD

**Issue by willemw12** [trapexit/mergerfs-tools#54]
mergerfs.fsck detects but does not report when there are two different files with the same name in the pool.

Possible fix, add a print statement:

    def check_consistancy(fullpath,verbose,size,fix):
        ...
        if (size and not size_equal(stats)):
    >       if verbose:
    >           print("%s (filename collision)" % fullpath)
            return

**Comment by trapexit** [comment]
I think what should be done is that if the sizes are different then don't ignore the files if the stats are the same. And perhaps change '--size' to something which checks if they are the same file.

**Comment by willemw12** [comment]
You mean fix the file content instead of only reporting the inconsistency? Mergerfs.fsck is for fixing meta-data, not the file content, right?

**Comment by trapexit** [comment]
Yes. mergerfs.fsck only focuses on metadata but could be extended to look for data inconsistencies as well.

**Comment by trapexit** [comment]
Should use `mergerfs.dedup` for this usecase.
