### ISSUE TITLE
mergerfs.balance | Scatter data?

### ISSUE THREAD

**Issue by broizter** [trapexit/mergerfs-tools#61]
Is it possible to use mergerfs.balance to scatter data? I want to select one drive as the source, and them spread the files out evenly to the rest of the drives so the source drives becomes empty or atleast clears out as much files as possible before filling the others.

**Comment by trapexit** [comment]
You mean to empty, not simply move / scatter.

No, it doesn't. Just mount the pool without the drive in question and rsync from the drive into the pool.

**Comment by trapexit** [comment]
This topic was discussed in an already open issue. Creating a tool that does this in a way that covers everyone's need isn't feasible. Especially when at its core is just mounting the pool again and running mv or rsync.

That said it seems people keep asking even though it's a simple process. I guess I can write more docs and a small app that just walks people through the process.

**Comment by broizter** [comment]
You're right, empty is a better word. Would be awesome if you could put something together but otherwise I will just use the method you mentioned in the first reply. Thanks! :)
