### ISSUE TITLE
mergerfs.dup doesn't update existing copies

### ISSUE THREAD

**Issue by dafzor** [trapexit/mergerfs-tools#62]
When using `mergerfs.dup -c 2 test` on a mergerfs pool it creates a copy of the files, later if those files are updated running the command again does nothing meaning there's two different versions of the file.

This behavior should be made very clear in bold text on the readme as most people would likely assume that the copies would be kept in sync by running the duplication tool again (it's what I assumed and was testing in a vm to verify).

Additionally the mergerfs.dedup only has a default to remove the newest file which will be the current copy, meaning that there's a serious potential for users to destroy their data by running it as it will delete the current version of their data while leaving the first copy that was made with mergerfs.dup.

**Comment by trapexit** [comment]
Please file separate tickets for unrelated and separate issues.

Regarding dup. Yes. It ignores changes because mergerfs doesn't manage that situation either. Only one file is selected for opening and use. It would need additional logic to select which to choose to copy around.

re: dedup. You are misunderstanding the behavior. The `-d` argument is what file to **keep** as the help mentions. Not what to remove. Also the default behavior is a noop and you need to add **--execute** to have it actually remove anything.

**Comment by dafzor** [comment]
I was going by my test where dedup removed the newer file instead of keeping it. I was mentioning it as a side note has I figured it all behavior described was by design, thus my report intent is to simply make documentation clearer.

Also, if i'm understanding this _"mergerfs doesn't manage that situation either."_ does that mean unmounting and mounting a volume could result in different versions of the file being selected for write? If that's the case is mergerfs.dup meant exclusively for WORM data?

**Comment by trapexit** [comment]
I just tested dedup by touching two files in the same relative path on two different drives and ran

```
$ mergerfs.dedup -vv -d newest /media/tmp
/media/tmp/foobar
  1: /mnt/8.0TB-00/tmp/foobar
   - uid:  1000; gid:  1000; mode: 100664; size: 0.0B; mtime: 1543276380.5871787
  2: /mnt/8.0TB-01/tmp/foobar
   - uid:  1000; gid:  1000; mode: 100664; size: 0.0B; mtime: 1543276386.1991296
would remove /mnt/8.0TB-00/tmp/foobar
Total savings: 0.0B
```

Which is what is expected. Kept the newest file.

**Comment by trapexit** [comment]
Yes, of course it would change what file is selected if you changed what files were available to it or the metrics on which it is selected. There are policies which dictate the file selected and if you change the input to that policy the output can change.

These tools are just thrown together for random tasks I've had and figured I'd share. mergerfs is designed for archival'ish use cases as described in the main docs. So when I wrote dup... yes... it was for data that isn't changing so it doesn't check the metadata of the files when dup'ing. It just checks how many copies there are and will copy to more drives if possible to hit the number selected.

If you want something which tracks changes and like dedup offers policies on which to copy around in case they differ... that will need to be created or mergerfs.dup changed to handle that.

**Comment by trapexit** [comment]
Can you use `-vv` so the timestamps are shown?

**Comment by dafzor** [comment]
```
root@omv:/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87# mergerfs.dedup -vv -d newest test
/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87/test/file2.txt
  1: /srv/dev-disk-by-label-pool1/test/file2.txt
   - uid:  1000; gid:   100; mode: 100664; size: 37.0B; mtime: 1543268170.4248412
  2: /srv/dev-disk-by-label-pool2/test/file2.txt
   - uid:  1000; gid:   100; mode: 100664; size: 23.0B; mtime: 1543268170.4248412
would remove /srv/dev-disk-by-label-pool1/test/file2.txt
/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87/test/file3.txt
  1: /srv/dev-disk-by-label-pool1/test/file3.txt
   - uid:  1000; gid:   100; mode: 100664; size: 10.0B; mtime: 1543266663.4165187
  2: /srv/dev-disk-by-label-pool2/test/file3.txt
   - uid:  1000; gid:   100; mode: 100664; size: 10.0B; mtime: 1543266663.4165187
would remove /srv/dev-disk-by-label-pool1/test/file3.txt
/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87/test/new.txt
  1: /srv/dev-disk-by-label-pool1/test/new.txt
   - uid:  1000; gid:   100; mode: 100664; size: 44.0B; mtime: 1543278594.3181763
  2: /srv/dev-disk-by-label-pool2/test/new.txt
   - uid:  1000; gid:   100; mode: 100664; size: 4.0B; mtime: 1543278594.3181763
would remove /srv/dev-disk-by-label-pool1/test/new.txt
Total savings: 91.0B
root@omv:/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87#
```
and right after i tried to touch the file and run the command again
```
root@omv:/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87# touch test/new.txt
root@omv:/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87# mergerfs.dedup -vv -d newest test
/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87/test/file2.txt
  1: /srv/dev-disk-by-label-pool1/test/file2.txt
   - uid:  1000; gid:   100; mode: 100664; size: 37.0B; mtime: 1543268170.4248412
  2: /srv/dev-disk-by-label-pool2/test/file2.txt
   - uid:  1000; gid:   100; mode: 100664; size: 23.0B; mtime: 1543268170.4248412
would remove /srv/dev-disk-by-label-pool1/test/file2.txt
/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87/test/file3.txt
  1: /srv/dev-disk-by-label-pool1/test/file3.txt
   - uid:  1000; gid:   100; mode: 100664; size: 10.0B; mtime: 1543266663.4165187
  2: /srv/dev-disk-by-label-pool2/test/file3.txt
   - uid:  1000; gid:   100; mode: 100664; size: 10.0B; mtime: 1543266663.4165187
would remove /srv/dev-disk-by-label-pool1/test/file3.txt
/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87/test/new.txt
  1: /srv/dev-disk-by-label-pool1/test/new.txt
   - uid:  1000; gid:   100; mode: 100664; size: 58.0B; mtime: 1543279440.388
  2: /srv/dev-disk-by-label-pool2/test/new.txt
   - uid:  1000; gid:   100; mode: 100664; size: 4.0B; mtime: 1543279440.388
would remove /srv/dev-disk-by-label-pool1/test/new.txt
Total savings: 105.0B
root@omv:/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87#
```

**Comment by trapexit** [comment]
You touched the file via mergerfs? Default is to apply some of what touch is to all files found. Dedup was told to look at the timestamp. Since the files have the same timestamp there is nothing to differentiate on.

The fsck tool is intended to deal with out of sync files across drives. Manual mode can be used to handle this as well or a timestamp + size sorting. That still isn't prefect however.

**Comment by dafzor** [comment]
`/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87` is the mount point for the mergerfs volume that openmediavault plugin created. I simply ran a touch on the pool volume. I've tried mergerfs.fsck but it does nothing.
```
root@omv:/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87# mergerfs.dedup -vv -d newest test
/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87/test/file2.txt
  1: /srv/dev-disk-by-label-pool2/test/file2.txt
   - uid:  1000; gid:   100; mode: 100664; size: 23.0B; mtime: 1543268170.4248412
  2: /srv/dev-disk-by-label-pool1/test/file2.txt
   - uid:  1000; gid:   100; mode: 100664; size: 37.0B; mtime: 1543268170.4248412
would remove /srv/dev-disk-by-label-pool2/test/file2.txt
/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87/test/file3.txt
  1: /srv/dev-disk-by-label-pool2/test/file3.txt
   - uid:  1000; gid:   100; mode: 100664; size: 10.0B; mtime: 1543266663.4165187
  2: /srv/dev-disk-by-label-pool1/test/file3.txt
   - uid:  1000; gid:   100; mode: 100664; size: 10.0B; mtime: 1543266663.4165187
would remove /srv/dev-disk-by-label-pool2/test/file3.txt
/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87/test/new.txt
  1: /srv/dev-disk-by-label-pool2/test/new.txt
   - uid:  1000; gid:   100; mode: 100664; size: 4.0B; mtime: 1543280172.216
  2: /srv/dev-disk-by-label-pool1/test/new.txt
   - uid:  1000; gid:   100; mode: 100664; size: 58.0B; mtime: 1543280172.216
would remove /srv/dev-disk-by-label-pool2/test/new.txt
Total savings: 37.0B
root@omv:/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87# mergerfs.fsck -v -f manual test
root@omv:/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87# mergerfs.ctl info
- mount: /srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87
  version: 2.24.2
  pid: 570
  srcmounts:
    - /srv/dev-disk-by-label-pool2
    - /srv/dev-disk-by-label-pool1
root@omv:/srv/e10b8c22-42bf-483f-b0a8-b743b29a7f87#
```
This is all new to me so I may very well doing something silly, in the meantime I've also rebooted the server which swapped the overlay order meaning the pool now shows the older file. 

So as far as I can tell mergerfs.dup can only be safely used in read only datasets.

**Comment by trapexit** [comment]
Looks like fsck ignores size differences. It focuses on permissions / uid:gid. Dedup looks at size. I suppose fsck could also check for files being the wrong size and offer removal or copying.

You aren't doing something silly but you aren't following exactly what the result is of certain actions (like touch). These tools are meant mostly for one time cleanups and such. mergerfs in general is not intended to be used with overlapping files of different types. It mentions in the docs that can be lead ot weird issues. If you wish for the tools to be expanded in certain ways then create tickets for each feature and describe in detail what you'd like to see.

**Comment by dafzor** [comment]
What I was trying to do was to have a mergerfs pool of data that's mostly discardable with a "mirrored" folder to provide some hardware failure resilience to some important files without having to sacrifice too much storage since most of my data does not require backup by mergerfs.dup over N disks.

But the question I had was how it would behave when a duplicate file got updated (thus the touch), which these tests have answered.

I realised that mergerfs-tools is simply not intended for what I was trying to do which is why from the start I was only suggesting that the existing documentation be improve to make it clear for "the next me" that trying to use mergerfs.dup for anything more then WORM archives is a terrible idea and will simply not work.

**Comment by trapexit** [comment]
Doing what you're looking for would require something far more complex like Unison or some more complicated rsync. Especially if you're looking to delete files.

That said... if all you want is a more complicated comparison in dedup to check if the files are in fact the same... it's not hard. Just tell create a ticket with precise functional requirements.

**Comment by trapexit** [comment]
Overwriting, copying, and pruning added.
