### ISSUE TITLE
mergerfs.dedup should not delete0 different files without additional flag

### ISSUE THREAD

**Issue by dafzor** [trapexit/mergerfs-tools#64]
From my understanding of the documentation and code, the dedup function should remove duplicate files, however even though it checks for size and md5 it will only exit when the file is the same (relevant code bellow)

    stats = stat_files(paths)
    if ((ignore == 1) and size_equal(stats)):
        if verbose:
            print('ignored:',fullpath)
        return 0
    if ((ignore >= 2) and md5sums_equal(paths)):
        if verbose:
            print('ignored:',fullpath)
        return 0

To prevent potential data loss I propose that the function should have an additional check like this: 

    if (not md5_sums_equal(path) and not force_flag) or (not size_equal(stats) and not force_flag):
        print('aborting operation, file mismatch:', fullpath)
        pring('run the dedup again with --force to ignore') 
        return 0

This way the user would be made aware of potential data loss and be fully of aware of the potential risk. It's also possible this might spare data loss in case of "data rot" had corrupted one of the files.

**Comment by trapexit** [comment]
"the dedup function should remove duplicate files"

Define "duplicate". Its checking what files exist at a specific relpath across the pool. The point of the "ignore" feature is to skip files you've used "dup" on. You are ignoring the files you explicitly wanted duplicated. So when enabled it ignore files which are identical. Otherwise it will call the dedup function as defined by the user on the found relpath files.

You're asking for "ignore different" rather than "ignore the same".

**Comment by trapexit** [comment]
I wrote dedup to clean up files which didn't match across drives. Not to clean up files that did. Both are valid but I had no need at the time for the latter. The change should be expanding the ignoring behavior and perhaps the dedup function to consider more things.

**Comment by dafzor** [comment]
I assumed dedup was the reverse operation of dup. And the existing documentation don't dispel that assumption.

Due to the serious risk of data loss I ask you to consider my suggestion to safeguard less "cautious" users. Specially considering what made me first aware of mergerfs-tools was [a discussion comparing it to greyhole](https://www.reddit.com/r/DataHoarder/comments/7n8gtm/greyhole_and_mergerfs/ds02hr5/) which is also an incorrect comparison.

**Comment by trapexit** [comment]
It is the reverse of dup. It just has options which change the behavior. It dedups files at the same relpath. You're asking for it to **not** dedup if files are different vs the default behavior of deduping anything found.

If you're deleting files automatically there is of course a risk of data loss. The risk is related to the thoroughness of the algo. There is no special risk of loss using dedup. It looks for files which exist across the drives and will keep one of them based on a user selected algo. You want to only dedup files which have the same data. The definition of "the same file" is simply the name. Not the content. Hence the filesize and md5sum checks.

**Comment by trapexit** [comment]
The names are the same. The content and metadata is possibly different. If the content could be kept in sync there would be no need for fsck or the options in the dedup tool.

I'll add clarification of what "dup" means but I'd prefer to enhance dup and dedup rather than scare people by saying it will randomly delete stuff.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs-tools/blob/dup/src/mergerfs.dup

How about this?

It will pick the file with the largest mtime or if they are all the same, the largest ctime or if they are all the same, the largest file. It will overwrite or copy to other branches in the pool upto the count provided (but ATM does not remove extras above that value).

**Comment by dafzor** [comment]
That sounds like a good solution, only think i feel might be missing is a quick way to check if there's "inconsistent" (read different) duplicate files, maybe getting the rsync command and doing a --dry-run will do it, guess I need to read the manual on that one.

**Comment by dafzor** [comment]
It occured to me that newer files can also be smaller (saving an image with better compression) so perhaps going by size as a last resort might be a "dangerous" guess and the safer option would be to just error out and let the user deal with it by hand?

**Comment by trapexit** [comment]
mtime and ctime are not always the same. They are the same due to whatever you're doing. 

As I mentioned before mergerfs only does what it's told. If an app is updating timestamps and the policy is `epall` then it will update all. The policy is in your control and mergerfs can't control what apps ask of it.

**Comment by trapexit** [comment]
"An alternative "hack" could also be going by the current file in the mergerfs mountpoint has the latest, but a remount could flip the order."

What do you mean "the current file"? Files are selected by the policy. Every function has a different policy. If you mean `getattr` then sure... it could use that instead of largest. 

" a remount could flip the order." you've said this multiple times but I don't understand what you mean. functions have policies. The file the function is applied to is based on that policy. If the settings change then the file selected could change. Depends on your settings.

**Comment by dafzor** [comment]
I'm using OpenMediaVault with the mergerfs plugin installed and options: `"defaults,allow_other,direct_io,use_ino"`, 4G free, "most free space" on 3 btrfs volumes.

I'm updating the file on a share configured on the mergerfs pool via samba or bash with touch. Since I kept to defaults I'm assuming everything is acting as it should?

> "What do you mean "the current file"? Files are selected by the policy. Every function has a different policy. If you mean getattr then sure... it could use that instead of largest."

	root@omv:/srv# ls -la */share/stuff.txt
	-rw-rw-r-- 1 nobody nogroup 20 Dec 15 22:07 41ee8fb8-292c-41cd-a38f-08e110e5952a/share/stuff.txt
	-rw-rw-r-- 1 nobody nogroup 20 Dec 15 22:07 dev-disk-by-label-pool1/share/stuff.txt
	-rw-rw-r-- 1 nobody nogroup  7 Dec 15 22:07 dev-disk-by-label-pool2/share/stuff.txt
	-rw-rw-r-- 1 nobody nogroup  7 Dec 15 22:07 dev-disk-by-label-pool3/share/stuff.txt

this is a ls done on the /srv folder in OpenMediaVault, which is the default mount point for every volume added.

41ee8fb8-292c-41cd-a38f-08e110e5952a is the merferfs pool and dev-disk-by-label-pool# are it's members. As I ls all of them I see the mergerfs shows me a file with 20kb, pool1 hdd has a file with 20kb but the other two copies have 7kb. So as it stands the file I'm actually editing on the mergerfs "view" is the file on the pool1 volume, changes get made to that file and every copy has it's ctime and mtime updated.

So that's what i mean by current file, the file in the volume that the mergerfs combined pool is currently pointing to.

> " a remount could flip the order." you've said this multiple times but I don't understand what you mean. 

In my understanding mergerfs combined pool presents the first file  in the volume list and that's the one that can be read and written. so in my case it would present the first file found in pool1, pool2 and pool3 volumes and update that one.

	root@omv:~# ls -la /srv/*/test/*
	-rw-rw-r-- 1 nobody users 36 Dec 15 22:59 /srv/41ee8fb8-292c-41cd-a38f-08e110e5952a/test/rtest.txt
	-rw-rw-r-- 1 nobody users 36 Dec 15 22:59 /srv/dev-disk-by-label-pool2/test/rtest.txt
	-rw-rw-r-- 1 nobody users 16 Dec 15 22:59 /srv/dev-disk-by-label-pool3/test/rtest.txt
	root@omv:~# echo "editing the file" >> /srv/41ee8fb8-292c-41cd-a38f-08e110e5952a/test/rtest.txt
	root@omv:~# ls -la /srv/*/test/*
	-rw-rw-r-- 1 nobody users 53 Dec 15 23:01 /srv/41ee8fb8-292c-41cd-a38f-08e110e5952a/test/rtest.txt
	-rw-rw-r-- 1 nobody users 53 Dec 15 23:01 /srv/dev-disk-by-label-pool2/test/rtest.txt
	-rw-rw-r-- 1 nobody users 16 Dec 15 22:59 /srv/dev-disk-by-label-pool3/test/rtest.txt
	root@omv:~#

file in pool2 got updated wile pool3 is still the old one. What I've seen happen once was the mergerfs pool change the order, so instead of presenting the pool2 file it would show pool3 file so that's what I meant.

That said I was unable to reproduce it, so starting to wonder if perhaps during my testing i did something else that affected the mounting order of the mergerfs pool or perhaps it was some odd samba interaction...

**Comment by trapexit** [comment]
"In my understanding mergerfs combined pool presents the first file in the volume list and that's the one that can be read and written."

It works that way if its configure it as such. `ff` is the default for all search functions. Please read the docs. https://github.com/trapexit/mergerfs#functions--policies--categories

The ordering of drives is based on the user's input. If you use globs it will always be in the same order. The file selected is always based on the function called's policy which takes several things into account. Mounting or remounting has **no** impact on the file selection.

**Comment by trapexit** [comment]
Pushed a new version (same link) which uses the mergerfs' getattr policy to choose a file if mtimes and ctimes are the same. It also removes files after `count`.
