### ISSUE TITLE
Naive question about mergerfs.balance and hardlinks

### ISSUE THREAD

**Issue by FlorentLM** [trapexit/mergerfs-tools#75]
Hi,

I have a naive question about how balance handles hardlinks.

Let's say I have the following structure:

sda
  |
  |___ Folder A
  |___ Folder A2

sdb
  |
  |___ Folder B
  |___ Folder B2

Where files in folder A and A2 point to the same inodes (same story for B and B2).

If I do a mergerfs.balance on the sda-sdb merge, what will happen to my files? If, for example, content from B is moved to sda, will the corresponding hardlinks in B2 be broken? Will they be moved? If yes, to a newly created B2 directory into sda?

Many thanks in advance!

**Comment by trapexit** [comment]
It doesn't do anything special about files with >1 link count.

Links aren't "broken." The name is removed and the link count is reduced.

**Comment by FlorentLM** [comment]
So the actual data will be copied and may live on both drives?

**Comment by trapexit** [comment]
Yes
