### ISSUE TITLE
Deduplicating data on NTFS storage pool

### ISSUE THREAD

**Issue by slrslr** [trapexit/mergerfs-tools#82]
Hello,

my NTFS filesystem contains some duplicate files (even they have different file names) and they are distributed in various directories.

I am looking for the software that will build a storage pool out of my NTFS HDDs and that SW will not waste space on duplicates but only store that file data once and make kind of links so the files still shows as duplicate on resulting NTFS filesystem, but in reality will be stored only once on physical HDD.

I have ARM CPU architecture and 512MB free RAM

**Comment by trapexit** [comment]
This isn't a mergerfs issue. 

There are lots of dedup'ing tools around. They generally should work fine with mergerfs. rdfind and fdupes are two that come to mind.

**Comment by slrslr** [comment]
I want to leave duplicates visible (on resulting pooled filesystem), only physical data should be written once. Symlinks is not a solution for me.

**Comment by trapexit** [comment]
You aren't exactly explaining what you're trying to accomplish. You asked for links. There are hard and soft links.

**Comment by slrslr** [comment]
I am trying to accomplish storage "pool" out of several drives that can contain duplicate files, but in fact only single file will take physical space. As said symbolic links are not solution because the app that i am using is not properly reading file that is a symlink and hardlink i can not currently use because it works within single drive, not within two drives which i am now using, so i a looking for storage pool where i combine drives and lets say daily or weekly i will run some task which will make sure big dumplicate files does not take unnecessary physical disk space on my drive pool.
Also i need drive pool contents be encrypted when computer is not running.

**Comment by trapexit** [comment]
If you're merging drives why would you care about hardlinks not working cross drive? Hard links will work just fine in that the file would exist on one drive and the path would be created to match other drives and a hard link created on the drive with the file. The dup file would be deleted.
