### ISSUE TITLE
Cannot make mergerfs.balance to work

### ISSUE THREAD

**Issue by kevindd992002** [trapexit/mergerfs-tools#83]
So I copied mergerfs.balance to /usr/local/bin, made it executable and here's what I get when trying to run it:

```
root@epsilon:/usr/local/bin# mergerfs.balance /mnt/storage/
/usr/local/bin/mergerfs.balance: line 7: syntax error near unexpected token `newline'
/usr/local/bin/mergerfs.balance: line 7: `<!DOCTYPE html>'
```

What does that mean? I also have have python3 and rsync installed, btw:

python3/stable,now 3.5.3-1 amd64 [installed,automatic]
rsync/stable,stable,now 3.1.2-1+deb9u1 amd64 [installed,automatic]

**Comment by kevindd992002** [comment]
Even mergerfs.balance -h produces the same error. Can there be a bug in the code itself?

**Comment by trapexit** [comment]
Looks to me you didn't download it. You downloaded the website. 

You have to use `git clone`, download via the raw file link, or download the zip.

![image](https://user-images.githubusercontent.com/197676/56454213-569e6a00-631b-11e9-9c2b-65e237fd0918.png)

**Comment by kevindd992002** [comment]
Well, this is what I did:

wget https://github.com/trapexit/mergerfs-tools/tree/master/src/mergerfs.balance

That's suppose to download the file, right?

**Comment by trapexit** [comment]
No. That's a website for the file. As I said you have to download via git, the raw link, or use the "Clone or download" "Download ZIP" link.

**Comment by kevindd992002** [comment]
Ok got it:

wget https://raw.githubusercontent.com/trapexit/mergerfs-tools/master/src/mergerfs.balance

When using balance though, will it replicate what one will expect if data is moved to the 3TB/8TB drives pool from scratch? Or will it just balance it in such a way that data size is more or less equal for both drives?

**Comment by trapexit** [comment]
It does what the docs say: `Will move files from the most filled drive (percentage wise) to the least filled drive. Will do so till the most and least filled drives come within a user defined percentage range (defaults to 2%).`

**Comment by kevindd992002** [comment]
Ok. Last question about this:

Will there be any repercussions if I do the balance while users are accessing data? What happens if a user is playing a media file while that file is set to be balanced to the other empty drive?

**Comment by trapexit** [comment]
Nothing will happen. I'm guessing you aren't familiar with POSIX filesystems. open files aren't impacted by being unlinked.

**Comment by kevindd992002** [comment]
Yes, you're 100% right, I'm not familiar with Linux. I'm a Windows guy that is trying to create a good NAS for my needs. Do you mean the files are simply skipped if they are used?

Also, the mergerfs.balance just finished its operation but this what I see:

```
**root@epsilon:~# du -hs /mnt/*
1.9T    /mnt/disk1
674G    /mnt/disk2
2.6T    /mnt/parity1
2.6T    /mnt/storage
**

Why am I seeing a significant discrepancy between disk1 and disk2? By default, it should be within 2% range difference and that's nowhere 2%.What am I doing wrong?
```

**Comment by kevindd992002** [comment]
Ok, I think I kinda understand it now.  The 2% default you're talking about is the difference in freespace range between the two drives. I'm not sure if it was just me but the documentation regarding the percentage is not easily understood. Perhaps an example in the documentation would be helpful. Just a suggestion, no pun intended.

**Comment by trapexit** [comment]
> Do you mean the files are simply skipped if they are used?

No. If a file is unlinked (removed) and still open its fine. It's not like Windows where you can't delete the file. 

Not sure how else to explain the behavior. It says it acts on percentages. It moves files from the largest filled drive % wise to the lowest until the difference between the % is at or below the set value.

**Comment by kevindd992002** [comment]
I see. When you say "it's fine", do you mean it will still move it succesfully to the lowest filled drive and remove it successfully from the highest filled drive?

Right, I understand how the percentage works already.

**Comment by trapexit** [comment]
It's. It's fine... Nothing negative happens. Everything works.
