### ISSUE TITLE
UnicodeEncodeError in mergerfs.balance

### ISSUE THREAD

**Issue by azilber** [trapexit/mergerfs-tools#89]
Running mergerfs.balance -p 50 /mnt/pool after a while results in:

file: ebooks/Nonfiction 1700 Sorted Ebooks Pack PHC/0786424834.McFarland.Science.Fiction.Television.Series.1990-.2004.Dec.2008.pdf
from: /mnt/wdblack1
to:   /mnt/samsung1
rsync -avlHAXWES --relative --progress --remove-source-files '/mnt/wdblack1/./ebooks/Nonfiction 1700 Sorted Ebooks Pack PHC/0786424834.McFarland.Science.Fiction.Television.Series.1990-.2004.Dec.2008.pdf' /mnt/samsung1/
sending incremental file list
ebooks/Nonfiction 1700 Sorted Ebooks Pack PHC/0786424834.McFarland.Science.Fiction.Television.Series.1990-.2004.Dec.2008.pdf
     5606733 100%   81.78MB/s    0:00:00 (xfer#1, to-check=0/3)

sent 5607660 bytes  received 33 bytes  11215386.00 bytes/sec
total size is 5606733  speedup is 1.00
Traceback (most recent call last):
  File "/usr/local/bin/mergerfs.balance", line 280, in <module>
    main()
  File "/usr/local/bin/mergerfs.balance", line 267, in main
    print('file: {}\nfrom: {}\nto:   {}'.format(relfilepath,fromdrive,todrive))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb7' in position 64: surrogates not allowed

**Comment by trapexit** [comment]
Ugh. The whole text encoding thing is a PITA. Let me see what I can do. Can you provide me the filename so I can test?

**Comment by azilber** [comment]
Here's an strace of the command failing:  http://dpaste.com/3BZKKBE

**Comment by azilber** [comment]
Looks like the actual file from the strace was:
/mnt/wdblack1/ebooks/Nonfiction 1700 Sorted Ebooks Pack PHC/0787637904.U\267X\267L.American.Revolution.Primary.Sources.Edition.1.Jun.2000.pdf

That file seems to be:  0787637904.U·X·L.American.Revolution.Primary.Sources.Edition.1.Jun.2000.pdf

**Comment by trapexit** [comment]
Can you try: https://raw.githubusercontent.com/trapexit/mergerfs-tools/encoding/src/mergerfs.balance

**Comment by aravenel** [comment]
For what its worth, I was getting the exact same error, and this update fixed it.

**Comment by trapexit** [comment]
OK. Looks like the filename is not utf8 and can't be properly decoded so it barfs. That patch makes it just pass it through in effect. I'll go through and add it to all the tools.

**Comment by azilber** [comment]
I can confirm the version posted above fixed my issues as well.
