### ISSUE TITLE
how to use fsck.mergerfs

### ISSUE THREAD

**Issue by IronicBadger** [trapexit/mergerfs-tools#9]
feeling dumb. how do i actually execute fsck on my pool?

**Comment by trapexit** [comment]
`fsck.mergerfs -h`

The tool needs more work but....

`fsck.mergerfs -v -f manual <mergerfs_mount_point>`

**Comment by IronicBadger** [comment]
No module named `xattr`

**Comment by trapexit** [comment]
You need to install the python xattr module.

On debian `apt-get install python-xattr`

**Comment by IronicBadger** [comment]
I could've probably googled xattr thing. Sorry. 

```
alex@epsilon:~/git/other/mergerfs-tools/src$ ./fsck.mergerfs -v -f manual /mnt/storage
/mnt/storage is not a mergerfs device
alex@epsilon:~/git/other/mergerfs-tools/src$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb1        46G   16G   29G  36% /
udev             10M     0   10M   0% /dev
tmpfs           3.2G  9.2M  3.2G   1% /run
tmpfs           7.9G  1.6M  7.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/sdb6       138G   44G   88G  34% /opt
mergerfs         14T  8.9T  4.9T  65% /mnt/storage
```

**Comment by trapexit** [comment]
It blanket checks certain errors so it is probably a false positive of a ENOENT error being thrown. It should only really do that if a file suddenly disappeared but.... like I said... these tools are a work in progress.

**Comment by IronicBadger** [comment]
No worries. Happy to test :)

**Comment by trapexit** [comment]
Take a look at the new version.

**Comment by jwaltrip4** [comment]
Do I need to run it with the --fix switch?

**Comment by trapexit** [comment]
Not what exactly you're asking. The arguments are listed in the docs and usage.

https://github.com/trapexit/mergerfs-tools#mergerfsfsck

**Comment by jwaltrip4** [comment]
Yes... but it does not really define what the fix statement does in detail, and it doees not way what happens when you omit the fix statement

I just want a report.

**Comment by trapexit** [comment]
The "fix" is defined in what it's checking as described. It says "metadata ... out of sync". "Permissions, ownership, etc." So a fix is ensuring that they are in sync. If you run without --fix it provides a report.
