### ISSUE TITLE
mergerfs.consolidate moves files to 2 of my 3 drives instead of from 3 drives to one drive

### ISSUE THREAD

**Issue by zombiehoffa** [trapexit/mergerfs-tools#91]
I'm trying to use consolidate to move stuff from spread across my 3  drives to one of my 3 drives and when I ran it it moved all the files (but left the directory structure) off of on of the three drives and wrote it to the other two drives. Running it again causes some moves but doesn't actually consolidate. Did I mess up running this on the physical mergerfs drive or did I mess it up in some other way? I used the following command directly on the directory in the mergerfs mount (when I run it on a subcomponent it errors out so I assume I did the right thing running it directly on the consolidated mergerfs mounts):
mergerfs.consolidate -m 999 -M 100G -e books

**Comment by trapexit** [comment]
Yes. You run these tools on the mergerfs mount.

Please show me the output. The tool consolidates data *per directory*. If you want to move data to other drives just use rsync from one drive to the other. Consolidate is meant for per directory collections. Not moving everything to one drive. That wouldn't make sense to turn into a special tool.

**Comment by zombiehoffa** [comment]
When  I pipe it to file it's quite large (because there are a large number of small files in the directory) I have included a snip of the rsync commands to show it's copying to different disks instead of all one disk.
![image](https://user-images.githubusercontent.com/627402/71611146-04714200-2b54-11ea-9e49-f1a085fef140.png)


That's one chunk of rsync commands, other ones  are copying from disk 3 to the other disks. If there's something else specific you are looking for in the output I can try to provide it. It would be great if one could specify which disk you want the files to end up on..

**Comment by trapexit** [comment]
I can't see what it's doing. It's cut off.

If all files from 1 relative path are ending up on 1 drive then that's what it's supposed to do.

>  It would be great if one could specify which disk you want the files to end up on.

Why? The point of this software is to take all files from one relative path and put them on one drive. Not to move all files from a path to one drive. That is a very different thing and can be done without much hassle using a single rsync command. There is no need for what this app does. If you want that just use rsync. I don't understand why you'd need a special tool for that.

**Comment by zombiehoffa** [comment]
Yes, the purpose of this is to take all the files spread across 3 drives
for a given directory by mergerfs but showing as one drive on the running
mergerfs and make them all end up on one physical drive within the mergerfs
correct? It's not doing that. It's writing files from drive one to drive 2,
drive 2 to drive 3,  and drive 3 to drive 1 all  in the same run of the
command.

**Comment by trapexit** [comment]
In a *single* directory? Not sub directories. Files in a single relative directory?

All files in /foo/bar across all drives end up on 1 drive. /foob/bar/baz is a *separate* thing.

**Comment by trapexit** [comment]
Show me the exact output of the command. I can not help you if I don't have a reproducible example.
