### ISSUE TITLE
Non recursive consolidator

### ISSUE THREAD

**Issue by thejinx0r** [trapexit/mergerfs-tools#95]
Following the discussion here:
https://github.com/trapexit/mergerfs/issues/709

I want to move files around, but not the folders, to match this new policy, I just want to move my files around, not the subfolders.
[mergerfs.consolidate](https://github.com/trapexit/mergerfs-tools/blob/master/src/mergerfs.consolidate) could work, but the rsync command is recursive so that my folders will get moved around too, because rsync will recurse on folders with the "-a" which implies recursion, but I could simply replace it with: "-lptgoD" (the same as -a without the recurse flag) which then won't recurse.
This will likely work (correct me if I'm wrong), and  could be useful for other people. If I make the changes: 
Should I give it a new name/tool? Or
Should I change the description of the consolidator so that it reflects this since now not all the data will be a on a single drive?

**Comment by trapexit** [comment]
rsync isn't doing any recursion. The tool is. The easiest way to get it to act on one directory is to add a flag to disable the os.walk by setting dirs = [].

**Comment by thejinx0r** [comment]
Got it. rsync is used to copy files, not folders, so the recursive option in rsync is meaningless.

**Comment by trapexit** [comment]
Doesn't mean your request is invalid. If you want it to only work on one directory rather than walking each sub directory I can add that.

**Comment by thejinx0r** [comment]
It does what I want it to do.
I didn't fully understand the code, so I had added a dry-run flag to look at what rsync was doing. 

The description:
> Consolidate files in a single mergerfs directory onto a single drive.
combined with the recursive flag made me think that all of the files and subfolders would be merged.
Rather, the actual behaviour is each subfolder will contain all of it's files on a single drive.
