### ISSUE TITLE
Erroring out when trying to run mergerfs.dedup on UnRAID server

### ISSUE THREAD

**Issue by TheEscPilot** [trapexit/mergerfs-tools#97]
Running using the command: (in the folder /usr/local/bin) 
mergerfs.dedup -d /mnt/user/mount_mergerfs/gdrive_nvfs/

Output: 
Traceback (most recent call last):
  File "./mergerfs.dedup", line 18, in <module>
    import ctypes
  File "/usr/lib64/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

Did I miss a step in setting this up? or is it a problem with my syntax

**Comment by trapexit** [comment]
That's not an error from mergerfs.dedup. Seems like something to do with the python install.

**Comment by TheEscPilot** [comment]
You sir, are correct. The issue was mine, UnRAID really doesn't wanna play well with others. 

You fixed this issue already in the UNRAID forums. I've parroted the solution in this post
https://forums.unraid.net/topic/89311-mergerfs-using-1500-1600-cpu/?tab=comments#comment-829420

Thanks for the speedy reply. 
Love your work.

**Comment by trapexit** [comment]
No problem. If you have any other issues feel free to reach out.
