### ISSUE TITLE
Move mergerfs out of my home folder

### ISSUE THREAD

**Issue by zilexa** [trapexit/mergerfs-tools#99]
Mergerfs is by default installed in the homefolder. Is it possible to move it to a location that is less visible for noob users that use the home folder for their personal files?
For example move it to a location where applications or system tools are installed?

**Comment by trapexit** [comment]
I'm not sure what you mean. Neither mergerfs or the mergerfs-tools are installed to a user's home directory.

1) They install to standard PREFIX/DESTDIR directories
2) The are no location aware. Just move them.

**Comment by zilexa** [comment]
there was a /mergerfs folder in my home directory. probably a remnant from the installation. I deleted it.
